name: Handle context across jobs and steps
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.output1 }}
      output2: ${{ steps.step2.outputs.output2 }}
    steps:
      - name: Set output1
        id: step1
        run: |
          echo "output1=Hello from job1" >> $GITHUB_OUTPUT
          # Echo outputs currently available
          echo "Available outputs: ${{ toJson(github.outputs) }}"

      - name: Set output2
        id: step2
        run: |
          echo "output2=Hello from step2" >> $GITHUB_OUTPUT
          # Echo outputs currently available
          echo "Available outputs: ${{ toJson(github.outputs) }}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Use output1 from job1
        run: |
          echo "Output from job1: ${{ needs.job1.outputs.output1 }}"
          # Echo outputs currently available
          echo "Available outputs: ${{ toJson(github.outputs) }}"

      - name: Use output2 from step2 in job1
        run: |
          echo "Output from step2 in job1: ${{ needs.job1.outputs.output2 }}"
          # Echo outputs currently available
          echo "Available outputs: ${{ toJson(github.outputs) }}"
