name: "01 - Building Blocks"
on: 
    # Push and workflow dispatch events
    push:
        branches:
            - "*"
    workflow_dispatch:
jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run: echo "Hello, World!"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Exit 0 step
              run: |
                exit 1
            - name: Say goodbye
              run: echo "Goodbye!"