name: 05 - 2 - Event Filters and Activity Types
on: 
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "This job runs on pull request closed events for the main branch."
  