name: 07 - Using Expressions
on: 
  workflow_dispatch:
    inputs:
      debug:
        description: "Enable debug mode"
        default: false
        type: boolean

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: ${{ inputs.debug }} Print start-up data
        if: ${{ inputs.debug }}
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
      
      - name: ${{ inputs.debug }} Print when triggered from ${{ github.ref }}
        if: ${{ github.ref_name == 'main' && inputs.debug }}
        run: |
          echo "This workflow was triggered from the main branch."
      
      - name: Print Hello
        run: echo "Hello, World!"