name: 08 - Using Variables
on: workflow_dispatch
env:
  WORKFLOW_VAR: "I am workflow env variable"
  OVERWRITTEN_VAR: "I will be overwritten"

jobs:
  echo:
    env:
      JOB_VAR: "I am job env variable"
      OVERWRITTEN_VAR: "I have been overwritten at the job level"
    runs-on: ubuntu-latest
    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: "I am step env variable"
          step_var2 : "I am another step env variable"
        run: |
          echo "Step env var: ${{ env.STEP_VAR }}"
          echo "Step env var 2: $step_var2"
          echo "Job env var: $JOB_VAR"
          echo "Workflow env var: $WORKFLOW_VAR"
          echo "Overwritten env var: $OVERWRITTEN_VAR"
      - name: Overwrite Job Variable
        env:
          OVERWRITTEN_VAR: "I have been overwritten at the step level"
        run: |
          echo "Overwritten env var: $OVERWRITTEN_VAR"
          